accounts/urls.py
from django.urls import path, include

from accounts.views import RegisterView, CooksListView

urlpatterns = [
    path("", include("django.contrib.auth.urls")),
    path(
        "cooks/",
        CooksListView.as_view(),
        name="cook-list",
    ),
    path("register/", RegisterView.as_view(), name="register"),
]

app_name = "accounts"

kitchen/urls.py
from django.urls import path

from kitchen.views import (
    DishListView,
    DishDetailView,
    DishCreateView,
    DishUpdateView,
    DishDeleteView,
    IndexView,
)

urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    path("dishes/", DishListView.as_view(), name="dish-list"),
    path("dishes/<int:pk>/", DishDetailView.as_view(), name="dish-detail"),
    path(
        "dishes/create/",
        DishCreateView.as_view(),
        name="dish-create",
    ),
    path(
        "dishes/<int:pk>/update/",
        DishUpdateView.as_view(),
        name="dish-update",
    ),
    path(
        "dishes/<int:pk>/delete/",
        DishDeleteView.as_view(),
        name="dish-delete",
    ),
    # path(
    #     "cooks/",
    #     CooksListView.as_view(),
    #     name="cook-list",
    # ),
    # path("register/", RegisterView.as_view(), name="register"),
]

app_name = "kitchen"

kitchen_restaurant/urls.py
import debug_toolbar
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("kitchen.urls", namespace="kitchen")),
    path("accounts/", include("accounts.urls", namespace="accounts")),
    path("__debug__/", include(debug_toolbar.urls)),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/includes/head.html
{% load static %}

<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
<title>Dish Manager</title>
<link rel="canonical" href="https://themesberg.com/product/admin-dashboard/volt-premium-bootstrap-5-dashboard">

<meta name="msapplication-TileColor" content="#ffffff">
<meta name="theme-color" content="#ffffff">

<!-- Volt CSS -->
<link type="text/css" href="{% static 'css/volt.css' %}" rel="stylesheet">

templates/includes/nav.html
{% load static %}

<nav class="navbar navbar-dark navbar-theme-primary px-4 col-12 d-lg-none">
  <div class="d-flex align-items-center">
    <button class="navbar-toggler d-lg-none collapsed" type="button" data-bs-toggle="collapse"
            data-bs-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false"
            aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  </div>
</nav>

templates/includes/navigation.html
{% load static %}

<nav class="navbar navbar-top navbar-expand navbar-dashboard navbar-dark ps-0 pe-2 pb-0">
  <div class="container-fluid px-0">
    <div class="d-flex justify-content-between w-100" id="navbarSupportedContent">
      <div class="d-flex align-items-center">
        <!-- Search form -->
        <form action="{% url 'kitchen:dish-list' %}" method="get"
              class="navbar-search form-inline" id="navbar-search-main">
          {% if user.is_authenticated %}
            <div class="input-group input-group-merge search-bar">
            <span class="input-group-text" id="topbar-addon">
              <svg class="icon icon-xs" x-description="Heroicon name: solid/search"
                   xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                <path fill-rule="evenodd"
                      d="M8 4a4 4 0 100 8 4 4 0 000-8zM2 8a6 6 0 1110.89 3.476l4.817 4.817a1 1 0 01-1.414 1.414l-4.816-4.816A6 6 0 012 8z"
                      clip-rule="evenodd"></path>
              </svg>
            </span>
            <input name="name" type="text" class="form-control" id="topbarInputIconLeft" placeholder="Search dishes"
                   aria-label="Search" aria-describedby="topbar-addon" value="{{ search_form.name.value }}">
            
            </div>
          {% endif %}  
        </form>
        <!-- / Search form -->
      </div>
      <!-- Navbar links -->
      <ul class="navbar-nav align-items-center">
        <li class="nav-item dropdown ms-lg-3">
          <a class="nav-link dropdown-toggle pt-1 px-0" href="#" role="button" data-bs-toggle="dropdown"
             aria-expanded="false">
            <div class="media d-flex align-items-center">
              <svg alt="Image placeholder" xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="#000000"
                   class="avatar rounded-circle bi bi-person-circle" viewBox="0 0 16 16">
                <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0"></path>
                <path fill-rule="evenodd"
                      d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8m8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1"></path>
              </svg>
              <div class="media-body ms-2 text-dark align-items-center d-none d-lg-block">
                <span class="mb-0 font-small fw-bold text-gray-900">{{ user.first_name }} {{ user.last_name }}</span>
              </div>
            </div>
          </a>
          {% if user.is_authenticated %}
            <div class="dropdown-menu dashboard-dropdown dropdown-menu-end mt-2 py-1">
            <div role="separator" class="dropdown-divider my-1"></div>
            <form method="post" action="{% url 'accounts:logout' %}?next={{ request.path }}">
              {% csrf_token %}
              <button class="dropdown-item d-flex align-items-center" type="submit">
                <svg class="dropdown-icon text-danger me-2" fill="none" stroke="currentColor" viewBox="0 0 24 24"
                     xmlns="http://www.w3.org/2000/svg">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                        d="M17 16l4-4m0 0l-4-4m4 4H7m6 4v1a3 3 0 01-3 3H6a3 3 0 01-3-3V7a3 3 0 013-3h4a3 3 0 013 3v1">
                  </path>
                </svg>
                Logout
              </button>
            </form>
          {% endif %}
          </div>
        </li>
      </ul>
    </div>
  </div>
</nav>

templates/includes/pagination.html
{% load query_transform %}

{% if is_paginated %}
  <div class="card-footer px-3 border-0 d-flex flex-column flex-lg-row align-items-center justify-content-between">
    <nav aria-label="Page navigation example">
      <ul class="pagination mb-0">
        {% if page_obj.has_previous %}
          <li class="page-item">
            <a class="page-link" href="?{% query_transform request page=page_obj.previous_page_number %}">Previous</a>
          </li>
        {% endif %}
        <li class="page-item active">
          <span class="page-link">{{ page_obj.number }} of {{ paginator.num_pages }}</span>
        </li>
        {% if page_obj.has_next %}
          <li class="page-item">
            <a class="page-link" href="?{% query_transform request page=page_obj.next_page_number %}">Next</a>
          </li>
        {% endif %}
      </ul>
    </nav>
  </div>
{% endif %}

templates/includes/scripts.html
{% load static %}

<!-- Core -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

<script src="https://unpkg.com/onscreen/dist/on-screen.umd.min.js"></script>

<!-- Datepicker -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/datepicker/1.0.10/datepicker.min.js"></script>

<!-- Moment JS -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.27.0/moment.min.js"></script>

<!-- Volt JS -->
<script src="{% static 'js/volt.js' %}"></script>

templates/includes/sidebar.html
{% load static %}

<nav id="sidebarMenu" class="sidebar d-lg-block bg-gray-800 text-white collapse" data-simplebar>
  <div class="sidebar-inner px-4 pt-3">
    <div class="user-card d-flex d-md-none align-items-center justify-content-between justify-content-md-center pb-4">
      <div class="d-flex align-items-center">
        <div class="d-block">
          <form method="post" action="{% url 'accounts:logout' %}?next={{ request.path }}">
            {% csrf_token %}
            <button class="btn btn-secondary btn-sm d-inline-flex align-items-center" type="submit">
              <svg class="icon icon-xxs me-1" fill="none" stroke="currentColor" viewBox="0 0 24 24"
                   xmlns="http://www.w3.org/2000/svg">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                      d="M17 16l4-4m0 0l-4-4m4 4H7m6 4v1a3 3 0 01-3 3H6a3 3 0 01-3-3V7a3 3 0 013-3h4a3 3 0 013 3v1"></path>
              </svg>
              Sign Out
            </button>
          </form>
        </div>
      </div>
      <div class="collapse-close d-md-none">
        <a href="#sidebarMenu" data-bs-toggle="collapse" data-bs-target="#sidebarMenu" aria-controls="sidebarMenu"
           aria-expanded="true" aria-label="Toggle navigation">
          <svg class="icon icon-xs" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
            <path fill-rule="evenodd"
                  d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z"
                  clip-rule="evenodd"></path>
          </svg>
        </a>
      </div>
    </div>
    <ul class="nav flex-column pt-3 pt-md-0">

      {% if user.is_authenticated %}
        <li class="nav-item">
          <a href="{% url 'kitchen:index' %}" class="nav-link">
        <span class="sidebar-icon">
            <svg class="icon icon-xs me-2" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
              <path d="M2 10a8 8 0 018-8v8h8a8 8 0 11-16 0z"></path>
              <path d="M12 2.252A8.014 8.014 0 0117.748 8H12V2.252z"></path>
            </svg>
          </span>
            <span class="sidebar-text">Home</span>
          </a>
        </li>
        <li class="nav-item">
          <a href="{% url 'kitchen:dish-list' %}" class="nav-link">
          <span class="sidebar-icon">
            <svg class="icon icon-xs me-2" fill="currentColor" viewBox="0 0 20 20"
                 xmlns="http://www.w3.org/2000/svg">
                <path fill-rule="evenodd"
                      d="M5 4a3 3 0 00-3 3v6a3 3 0 003 3h10a3 3 0 003-3V7a3 3 0 00-3-3H5zm-1 9v-1h5v2H5a1 1 0 01-1-1zm7 1h4a1 1 0 001-1v-1h-5v2zm0-4h5V8h-5v2zM9 8H4v2h5V8z"
                      clip-rule="evenodd"></path>
              </svg>
          </span>
            <span class="sidebar-text">Dishes</span>
          </a>
        </li>
        <li class="nav-item">
          <a href="{% url 'accounts:cook-list' %}" class="nav-link">
          <span class="sidebar-icon">
            <svg class="icon icon-xs me-2" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
              <path
                  d="M13 6a3 3 0 11-6 0 3 3 0 016 0zM18 8a2 2 0 11-4 0 2 2 0 014 0zM14 15a4 4 0 00-8 0v3h8v-3zM6 8a2 2 0 11-4 0 2 2 0 014 0zM16 18v-3a5.972 5.972 0 00-.75-2.906A3.005 3.005 0 0119 15v3h-3zM4.75 12.094A5.973 5.973 0 004 15v3H1v-3a3 3 0 013.75-2.906z">
              </path>
            </svg>
          </span>
            <span class="sidebar-text">Cooks</span>
          </a>
        </li>
      {% endif %}
    </ul>
  </div>
</nav>