kitchen/urls.py
from django.urls import path

from kitchen.views import (
    DishListView,
    DishDetailView,
    DishCreateView,
    DishUpdateView,
    DishDeleteView,
    IndexView,
)

urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    path("dishes/", DishListView.as_view(), name="dish-list"),
    path("dishes/<int:pk>/", DishDetailView.as_view(), name="dish-detail"),
    path(
        "dishes/create/",
        DishCreateView.as_view(),
        name="dish-create",
    ),
    path(
        "dishes/<int:pk>/update/",
        DishUpdateView.as_view(),
        name="dish-update",
    ),
    path(
        "dishes/<int:pk>/delete/",
        DishDeleteView.as_view(),
        name="dish-delete",
    ),
    # path(
    #     "cooks/",
    #     CooksListView.as_view(),
    #     name="cook-list",
    # ),
    # path("register/", RegisterView.as_view(), name="register"),
]

app_name = "kitchen"

kitchen_restaurant/urls.py
import debug_toolbar
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("kitchen.urls", namespace="kitchen")),
    path("accounts/", include("accounts.urls", namespace="accounts")),
    path("__debug__/", include(debug_toolbar.urls)),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

kitchen/models.py
from django.db import models

from accounts.models import Cook


class DishType(models.Model):
    name = models.CharField(max_length=55, null=False, blank=False)

    def __str__(self):
        return self.name


class Ingredient(models.Model):
    name = models.CharField(max_length=55, null=False, blank=False, unique=True)

    def __str__(self):
        return self.name


class Dish(models.Model):
    name = models.CharField(max_length=55, unique=True, null=False, blank=False)
    description = models.TextField(null=True, blank=True)
    price = models.DecimalField(max_digits=6, decimal_places=2, null=False, blank=False)
    dish_type = models.ForeignKey(
        DishType,
        on_delete=models.CASCADE,
        null=False,
        blank=False,
        related_name="dishes",
    )
    ingredients = models.ManyToManyField(Ingredient, blank=False, related_name="dishes")
    cooks = models.ManyToManyField(Cook, blank=False, related_name="dishes")

    def __str__(self):
        return f"{self.name}, ({self.dish_type}), {self.cooks}"

kitchen/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm

from .models import Dish, Ingredient, Cook


class DishNameSearchForm(forms.Form):
    name = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Search by name"}),
    )


class DishForm(forms.ModelForm):
    ingredients = forms.ModelMultipleChoiceField(
        queryset=Ingredient.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=True,
    )

    class Meta:
        model = Dish
        fields = ["name", "description", "price", "dish_type", "ingredients", "cooks"]
        widgets = {
            "name": forms.TextInput(
                attrs={"class": "form-control", "placeholder": "Enter dish name"}
            ),
            "description": forms.Textarea(
                attrs={"class": "form-control", "placeholder": "Enter dish description"}
            ),
            "price": forms.NumberInput(
                attrs={"class": "form-control", "placeholder": "Enter price"}
            ),
            "dish_type": forms.Select(attrs={"class": "form-control"}),
            "cooks": forms.SelectMultiple(attrs={"class": "form-control"}),
        }
        labels = {
            "name": "Dish Name",
            "description": "Description",
            "price": "Price (UA)",
            "dish_type": "Dish Type",
            "ingredients": "Ingredients",
            "cooks": "Assigned Cooks",
        }

    def clean_price(self):
        price = self.cleaned_data.get("price")
        if price is not None and price < 0:
            raise forms.ValidationError("Price cannot be negative.")
        return price

kitchen/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView,
    TemplateView,
)

from kitchen.forms import DishNameSearchForm, DishForm
from kitchen.models import DishType, Dish, Cook


class IndexView(LoginRequiredMixin, TemplateView):
    template_name = "kitchen/index.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update(
            {
                "total_types": DishType.objects.count(),
                "total_dishes": Dish.objects.count(),
                "total_cooks": Cook.objects.count(),
            }
        )
        return context


class DishListView(LoginRequiredMixin, ListView):
    paginate_by = 5

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(DishListView, self).get_context_data(**kwargs)
        name = self.request.GET.get("name", "")
        context["search_form"] = DishNameSearchForm(initial={"name": name})
        return context

    def get_queryset(self):
        queryset = (
            Dish.objects.select_related("dish_type")
            .prefetch_related("cooks")
            .order_by("name")
        )
        form = DishNameSearchForm(self.request.GET)

        if form.is_valid():
            return queryset.filter(name__icontains=form.cleaned_data["name"])

        return queryset


class DishDetailView(LoginRequiredMixin, DetailView):
    queryset = Dish.objects.prefetch_related("ingredients", "cooks").select_related(
        "dish_type"
    )
    model = Dish

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        dish = self.get_object()

        dish_ingredients = dish.ingredients.all()

        context["dish_ingredients"] = dish_ingredients
        return context


class DishCreateView(CreateView):
    model = Dish
    form_class = DishForm
    success_url = "/dishes/"


class DishUpdateView(LoginRequiredMixin, UpdateView):
    model = Dish
    form_class = DishForm
    success_url = reverse_lazy("kitchen:dish-list")


class DishDeleteView(LoginRequiredMixin, DeleteView):
    model = Dish
    success_url = reverse_lazy("kitchen:dish-list")

templates/kitchen/dish_confirm_delete.html
{% extends "base_old.html" %}
{% block content %}
  <h1>Delete Dish</h1>
  
  <p>Are you sure you want to delete this dish?</p>
  <p>Name: {{ dish.name }}</p>
  <a href="{% url "kitchen:dish-list" %}"><button class="btn btn-primary">Cancel</button></a>
  <br>
  <br>
  <form action="" method="post">
    {% csrf_token %}
    <input type="submit" value="Yes, delete" class="btn btn-danger" />
  </form>
{% endblock %}

templates/kitchen/dish_detail.html
{% extends "base.html" %}
{% load static %}

{% block content %}
  <div class="py-4 row">
    <div class="col-12 col-xl-8">
      <div class="card card-body border-0 shadow mb-4 mb-xl-0">
        <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center py-1">
          <h2 class="h4 mb-4">{{ dish.id }}. {{ dish.name }}</h2>
          <div>
            <a class="btn btn-primary" href="{% url 'kitchen:dish-update' pk=dish.id %}">
              <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pen"
                   viewBox="0 0 16 16">
                <path
                    d="m13.498.795.149-.149a1.207 1.207 0 1 1 1.707 1.708l-.149.148a1.5 1.5 0 0 1-.059 2.059L4.854 14.854a.5.5 0 0 1-.233.131l-4 1a.5.5 0 0 1-.606-.606l1-4a.5.5 0 0 1 .131-.232l9.642-9.642a.5.5 0 0 0-.642.056L6.854 4.854a.5.5 0 1 1-.708-.708L9.44.854A1.5 1.5 0 0 1 11.5.796a1.5 1.5 0 0 1 1.998-.001m-.644.766a.5.5 0 0 0-.707 0L1.95 11.756l-.764 3.057 3.057-.764L14.44 3.854a.5.5 0 0 0 0-.708z"></path>
              </svg>
            </a>
            <a class="btn btn-outline-danger " href="{% url 'kitchen:dish-delete' pk=dish.id %}">
              <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash"
                   viewBox="0 0 16 16">
                <path
                    d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5m2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5m3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0z"></path>
                <path
                    d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4zM2.5 3h11V2h-11z"></path>
              </svg>
            </a>
          </div>
        </div>
        <ul class="list-group list-group-flush">
          <li class="list-group-item d-flex align-items-center justify-content-between px-0 border-bottom">
            <div>
              <h2 class="h5 mb-1">Description:</h2>
              <p class="small pe-4">{{ dish.description }}</p>
            </div>
          </li>
          <li class="list-group-item d-flex align-items-center justify-content-between px-0">
            <div>
              <h4 class="h6 mb-1">Assigned Cooks:</h4>
              {% for cook in dish.cooks.all %}
                <p class="small pe-4">{{ cook.first_name }} {{ cook.last_name }} ({{ cook.username }})</p>
              {% endfor %}
            </div>
          </li>
        </ul>
      </div>
    </div>
    <div class="col-12 col-xl-4">
      <div class="card border-0 shadow">
        <div class="card-body">
{#          <div class="d-flex align-items-center justify-content-between pt-3">#}
{#            <div>#}
{#              <div class="h6 mb-0 d-flex align-items-center">#}
{#                Priority:#}
{#              </div>#}
{#              <div class="small card-stats">#}
{#                {{ dish.get_priority_display }}#}
{#                <svg class="icon icon-xs text-success" fill="currentColor" viewBox="0 0 20 20"#}
{#                     xmlns="http://www.w3.org/2000/svg">#}
{#                  <path fill-rule="evenodd"#}
{#                        d="M14.707 12.707a1 1 0 01-1.414 0L10 9.414l-3.293 3.293a1 1 0 01-1.414-1.414l4-4a1 1 0 011.414 0l4 4a1 1 0 010 1.414z"#}
{#                        clip-rule="evenodd"></path>#}
{#                </svg>#}
{#              </div>#}
{#            </div>#}
{#          </div>#}
          <div class="d-flex align-items-center justify-content-between pt-3">
            <div>
              <div class="h6 mb-0 d-flex align-items-center">
                Type:
              </div>
              <div class="small card-stats">
                {{ dish.dish_type }}
              </div>
            </div>
          </div>
          <div class="d-flex align-items-center justify-content-between pt-3">
            <div>
              <div class="h6 mb-0 d-flex align-items-center">
                Ingredients:
              </div>
              {% for ingredient in dish_ingredients %}
                <div class="small card-stats">
                    {{ ingredient.name }}
                </div>
              {% endfor %}
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

templates/kitchen/dish_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}
{% load static %}

{% block content %}
  <div class="py-4">
    <nav aria-label="breadcrumb" class="d-none d-md-inline-block">
      <ol class="breadcrumb breadcrumb-dark breadcrumb-transparent">
        <li class="breadcrumb-item">
          <a href="{% url 'kitchen:index' %}">
            <svg class="icon icon-xxs" fill="none" stroke="currentColor" viewBox="0 0 24 24"
                 xmlns="http://www.w3.org/2000/svg">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                    d="M3 12l2-2m0 0l7-7 7 7M5 10v10a1 1 0 001 1h3m10-11l2 2m-2-2v10a1 1 0 01-1 1h-3m-6 0a1 1 0 001-1v-4a1 1 0 011-1h2a1 1 0 011 1v4a1 1 0 001 1m-6 0h6">
              </path>
            </svg>
          </a>
        </li>
        <li class="breadcrumb-item active" aria-current="page">{{ object|yesno:"Update,Create" }} dish</li>
      </ol>
    </nav>
    <div class="d-flex justify-content-between w-100 flex-wrap">
      <div class="mb-3 mb-lg-0">
        <h1 class="h4">{{ object|yesno:"Update,Create" }} dish</h1>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-12 mb-4">
      <div class="card border-0 shadow components-section">
        <form action="" method="post" novalidate>
          <div class="card-body">
            {% csrf_token %}
            {{ form|crispy }}
            <input type="submit" value="Submit" class="btn btn-primary">
          </div>
        </form>
      </div>
    </div>
  </div>
{% endblock content %}

templates/kitchen/dish_list.html
{% extends "base.html" %}
{% load static %}

{% block content %}
  <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center py-4">
    <div class="d-block mb-4 mb-md-0">
      <nav aria-label="breadcrumb" class="d-none d-md-inline-block">
        <ol class="breadcrumb breadcrumb-dark breadcrumb-transparent">
          <li class="breadcrumb-item">
            <a href="{% url 'kitchen:index' %}">
              <svg class="icon icon-xxs" fill="none" stroke="currentColor" viewBox="0 0 24 24"
                   xmlns="http://www.w3.org/2000/svg">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                      d="M3 12l2-2m0 0l7-7 7 7M5 10v10a1 1 0 001 1h3m10-11l2 2m-2-2v10a1 1 0 01-1 1h-3m-6 0a1 1 0 001-1v-4a1 1 0 011-1h2a1 1 0 011 1v4a1 1 0 001 1m-6 0h6">
                </path>
              </svg>
            </a>
          </li>
          <li class="breadcrumb-item active" aria-current="page">Dishes</li>
        </ol>
      </nav>
      <h2 class="h4">Dishes</h2>
    </div>
    <div class="btn-toolbar mb-2 mb-md-0">
      <a href="{% url 'kitchen:dish-create' %}" class="btn btn-sm btn-gray-800 d-inline-flex align-items-center">
        <svg class="icon icon-xs me-2" fill="none" stroke="currentColor" viewBox="0 0 24 24"
             xmlns="http://www.w3.org/2000/svg">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 6v6m0 0v6m0-6h6m-6 0H6"></path>
        </svg>
        New Dish
      </a>
    </div>
  </div>
  <div class="table-settings mb-4">
    <form id="dish-search-form" action="" method="get" class="form-inline">
      <div class="row align-items-center justify-content-between">

        <div class="col col-md-6 col-lg-4 col-xl-4">
          <div class="input-group me-2 me-lg-3 fmxw-400">
          <span class="input-group-text">
            <svg class="icon icon-xs" x-description="Heroicon name: solid/search" xmlns="http://www.w3.org/2000/svg"
                 viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
              <path fill-rule="evenodd"
                    d="M8 4a4 4 0 100 8 4 4 0 000-8zM2 8a6 6 0 1110.89 3.476l4.817 4.817a1 1 0 01-1.414 1.414l-4.816-4.816A6 6 0 012 8z"
                    clip-rule="evenodd"></path>
            </svg>
          </span>
{#            <input name="assignee" type="text" class="form-control" placeholder="Search by assignee"#}
{#                   value="{{ search_form.assignee.value }}">#}
          </div>
        </div>
        <div class="col">
{#          <div class="form-check">#}
{#            <input name="include_completed" class="form-check-input" type="checkbox"#}
{#                   onclick="this.form.submit();"#}
{#                {% if search_form.include_completed.value %} checked {% endif %}>#}
{#            <label class="form-check-label" for="defaultCheck10">#}
{#              Include completed#}
{#            </label>#}
{#          </div>#}
        </div>
      </div>
    </form>
  </div>
  <div class="card card-body border-0 shadow table-wrapper table-responsive">
    <table class="table table-hover">
      <thead>
      <tr>
        <th class="border-gray-200">ID</th>
        <th class="border-gray-200">Name</th>
        <th class="border-gray-200">Dish Type</th>
        <th class="border-gray-200">Cookers</th>
        <th class="border-gray-200">Update</th>
        <th class="border-gray-200">Delete</th>
      </tr>
      </thead>
      <tbody>
      {% for dish in dish_list %}
        <tr>
          <td>
            {{ dish.id }}
          </td>
          <td>
            <a href="{% url "kitchen:dish-detail" pk=dish.id %}"><b>{{ dish.name }}</b></a>
          </td>
          <td>
            {{ dish.dish_type }}
          </td>
          <td>
            {{ dish.cooks.count }}
          </td>
          <td>
            <a style="color: #37ff00" href="{% url 'kitchen:dish-update' pk=dish.id %}">
              Update
            </a>
          </td>  
          <td>
            <a style="color: red" href="{% url 'kitchen:dish-delete' pk=dish.id %}">
              Delete
            </a>
          </td>
        </tr>
      {% endfor %}
      </tbody>
    </table>
  </div>
{% endblock content %}

templates/kitchen/index.html
{% extends "base.html" %}
{% load static %}

{% block content %}
  <div class="container vh-100"
       style="background-image: url({% static 'images/dashboard-bg.jpg' %}); background-size: cover;">
    <div class="row py-4">
    </div>
    <div class="row">
      <div class="col-12 col-sm-6 col-xl-4 mb-4">
        <div class="card border-0 shadow">
          <div class="card-body">
            <div class="row d-block d-xl-flex align-items-center">
              <div
                  class="col-12 col-xl-5 text-xl-center mb-3 mb-xl-0 d-flex align-items-center justify-content-xl-center">
                <div class="icon-shape icon-shape-primary rounded me-4 me-sm-0">
                    <svg fill="#000000" viewBox="0 0 32 32" xmlns="http://www.w3.org/2000/svg" id="Layer_1" data-name="Layer 1">
                        <g id="SVGRepo_bgCarrier" stroke-width="0"></g>
                        <g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round"></g>
                        <g id="SVGRepo_iconCarrier">
                            <path d="M8.49,12.68v4.61c0,.34,.23,.61,.53,.71v5.48c0,.13-.14,3.21,1.88,5.34,1.22,1.28,2.93,1.94,5.09,1.94s3.88-.65,5.09-1.94c2.02-2.13,1.89-5.21,1.88-5.3v-5.52c.3-.1,.53-.37,.53-.71v-4.61c1.71-.69,2.92-2.36,2.92-4.32,0-2.57-2.09-4.67-4.67-4.67-.49,0-.98,.08-1.46,.23-1.09-1.67-2.93-2.68-4.94-2.68s-3.68,.91-4.79,2.46c-2.74-.22-5.01,1.96-5.01,4.65,0,1.96,1.21,3.63,2.92,4.32Zm11.51,15.11c-.92,.97-2.27,1.46-4,1.46s-3.07-.49-4-1.46c-1.58-1.66-1.48-4.21-1.48-4.28v-5.48h10.96v5.51s.1,2.58-1.48,4.24Zm2.01-14.77v3.51H9.99v-3.51h12.02ZM10.23,5.19c.21,0,.4,.02,.59,.05,.3,.05,.61-.09,.77-.35,.81-1.34,2.22-2.15,3.78-2.15,1.68,0,3.19,.94,3.95,2.45,.09,.18,.25,.31,.43,.38,.19,.06,.39,.05,.57-.04,.45-.23,.95-.35,1.44-.35,1.75,0,3.17,1.42,3.17,3.17s-1.42,3.17-3.17,3.17H10.23c-1.75,0-3.17-1.42-3.17-3.17s1.42-3.17,3.17-3.17Z"></path>
                            <path d="M14.26,5.25c1.5,.28,2.59,1.59,2.59,3.11,0,.41,.34,.75,.75,.75s.75-.34,.75-.75c0-2.24-1.6-4.17-3.81-4.59-.4-.07-.8,.19-.88,.6-.08,.41,.19,.8,.6,.88Z"></path>
                            <circle cx="13.32" cy="20.07" r="1.25"></circle>
                            <circle cx="18.68" cy="20.07" r="1.25"></circle>
                            <path d="M17.56,24.5h-3.12c-.41,0-.75,.34-.75,.75s.34,.75,.75,.75h3.12c.41,0,.75-.34,.75-.75s-.34-.75-.75-.75Z"></path>
                        </g>
                    </svg>
                </div>
              </div>
              <div class="col-12 col-xl-7 px-xl-0">
                <div class="d-none d-sm-block">
                  <h2 class="h6 text-gray-400 mb-0">Cooks</h2>
                  <h3 class="fw-extrabold mb-2">{{ total_cooks }}</h3>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="col-12 col-sm-6 col-xl-4 mb-4">
        <div class="card border-0 shadow">
          <div class="card-body">
            <div class="row d-block d-xl-flex align-items-center">
              <div
                  class="col-12 col-xl-5 text-xl-center mb-3 mb-xl-0 d-flex align-items-center justify-content-xl-center">
                <div class="icon-shape icon-shape-secondary rounded me-4 me-sm-0">
                  <svg fill="#000000" viewBox="0 0 32 32" xmlns="http://www.w3.org/2000/svg" id="Layer_1" data-name="Layer 1"><g id="SVGRepo_bgCarrier" stroke-width="0"></g><g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round"></g><g id="SVGRepo_iconCarrier"><path d="M29.22,13.95h-.28v-2.07c0-4.75-5.76-8.61-12.84-8.61S3.26,7.14,3.26,11.88v2.07h-.48c-.84,0-1.52,.68-1.52,1.52v1.06c0,.84,.68,1.52,1.52,1.52h.48v2.07c0,4.74,5.76,8.6,12.84,8.6s12.84-3.86,12.84-8.6v-2.07h.28c.84,0,1.52-.68,1.52-1.52v-1.06c0-.84-.68-1.52-1.52-1.52ZM16.1,4.78c5.85,0,10.68,2.79,11.28,6.36H4.82c.6-3.57,5.43-6.36,11.28-6.36ZM4.76,12.63H27.44v1.32H4.76v-1.32Zm11.34,14.58c-5.85,0-10.68-2.79-11.28-6.35h12.49l1.8,3c.14,.23,.38,.36,.64,.36s.51-.14,.64-.36l1.8-3h5.17c-.6,3.56-5.43,6.35-11.28,6.35Zm11.34-7.85h-5.66c-.26,0-.51,.14-.64,.36l-1.38,2.29-1.38-2.29c-.14-.23-.38-.36-.64-.36H4.76v-1.32H27.44v1.32Zm1.78-2.82l-26.46-.02,.02-1.08h1.22s0,0,0,0H28.19s0,0,0,0h1.02s.02,.02,.02,.02l-.02,1.08Z"></path></g></svg>
                </div>
              </div>
              <div class="col-12 col-xl-7 px-xl-0">
                <div class="d-none d-sm-block">
                  <h2 class="h6 text-gray-400 mb-0">Total dishes</h2>
                  <h3 class="fw-extrabold mb-2">{{ total_dishes }}</h3>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="col-12 col-sm-6 col-xl-4 mb-4">
        <div class="card border-0 shadow">
          <div class="card-body">
            <div class="row d-block d-xl-flex align-items-center">
              <div
                  class="col-12 col-xl-5 text-xl-center mb-3 mb-xl-0 d-flex align-items-center justify-content-xl-center">
                <div class="icon-shape icon-shape-tertiary rounded me-4 me-sm-0">
                  <svg fill="#000000" viewBox="0 0 32 32" xmlns="http://www.w3.org/2000/svg" id="Layer_1" data-name="Layer 1"><g id="SVGRepo_bgCarrier" stroke-width="0"></g><g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round"></g><g id="SVGRepo_iconCarrier"><path d="M6.97,30.75H25.03c.41,0,.75-.34,.75-.75V3.89c0-.41-.34-.75-.75-.75h-2.56v-1.14c0-.41-.34-.75-.75-.75s-.75,.34-.75,.75v1.14h-4.22v-1.14c0-.41-.34-.75-.75-.75s-.75,.34-.75,.75v1.14h-4.22v-1.14c0-.41-.34-.75-.75-.75s-.75,.34-.75,.75v1.14h-2.56c-.41,0-.75,.34-.75,.75V30c0,.41,.34,.75,.75,.75Zm.75-26.11h1.81v1.14c0,.41,.34,.75,.75,.75s.75-.34,.75-.75v-1.14h4.22v1.14c0,.41,.34,.75,.75,.75s.75-.34,.75-.75v-1.14h4.22v1.14c0,.41,.34,.75,.75,.75s.75-.34,.75-.75v-1.14h1.81V29.25H7.72V4.64Z"></path><path d="M16.86,9.66h-6.57c-.41,0-.75,.34-.75,.75s.34,.75,.75,.75h6.57c.41,0,.75-.34,.75-.75s-.34-.75-.75-.75Z"></path><path d="M16.86,16.19h-6.57c-.41,0-.75,.34-.75,.75s.34,.75,.75,.75h6.57c.41,0,.75-.34,.75-.75s-.34-.75-.75-.75Z"></path><path d="M16.86,22.73h-6.57c-.41,0-.75,.34-.75,.75s.34,.75,.75,.75h6.57c.41,0,.75-.34,.75-.75s-.34-.75-.75-.75Z"></path><path d="M10.28,14.27h3.61c.41,0,.75-.34,.75-.75s-.34-.75-.75-.75h-3.61c-.41,0-.75,.34-.75,.75s.34,.75,.75,.75Z"></path><path d="M10.28,21h3.61c.41,0,.75-.34,.75-.75s-.34-.75-.75-.75h-3.61c-.41,0-.75,.34-.75,.75s.34,.75,.75,.75Z"></path><path d="M13.89,25.79h-3.61c-.41,0-.75,.34-.75,.75s.34,.75,.75,.75h3.61c.41,0,.75-.34,.75-.75s-.34-.75-.75-.75Z"></path></g></svg>
                </div>
              </div>
              <div class="col-12 col-xl-7 px-xl-0">
                <div class="d-none d-sm-block">
                  <h2 class="h6 text-gray-400 mb-0"> Dish types</h2>
                  <h3 class="fw-extrabold mb-2">{{ total_types }}</h3>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

{% endblock content %}